const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_NOTFOUND_STATUS = 404;
const HTTP_BAD_REQUEST_STATUS = 400;
const HTTP_UNAUTHORIZED_CLIENT_STATUS = 401;
const PORT = '3000';
const FILE_NAME = 'talker.json';

module.exports = {
  HTTP_OK_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_NOTFOUND_STATUS,
  HTTP_BAD_REQUEST_STATUS,
  HTTP_UNAUTHORIZED_CLIENT_STATUS,
  PORT,
  FILE_NAME,
};
