const PORT = '3000';

const HTTP_OK_STATUS = 200;
const HTTP_BAD_REQUEST = 400;
const HTTP_NOT_FOUND_STATUS = 404;

module.exports = { HTTP_OK_STATUS, HTTP_BAD_REQUEST, HTTP_NOT_FOUND_STATUS, PORT };
