const PORT = 3000;

const PATH_TALKER = 'talker.json';

const HTTP_OK_STATUS = 200;
const HTTP_CREATE_STATUS = 201;
const HTTP_BAD_REQUEST_STATUS = 400;
const HTTP_UNAUTHORIZED_STATUS = 401;
const HTTP_NOT_FOUND_STATUS = 404;

module.exports = {
  https: {
    HTTP_OK_STATUS,
    HTTP_NOT_FOUND_STATUS,
    HTTP_BAD_REQUEST_STATUS,
    HTTP_UNAUTHORIZED_STATUS,
    HTTP_CREATE_STATUS,
  },
  PORT,
  PATH_TALKER,
};
